spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo-app
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update #update the schema automatically to match the entity model
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQLDialect
        #It will generate a Queries specific to the MySQL